scrape_configs:
  - job_name: 'IncrementService'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:3333']
        labels:
          application: 'IncrementService'
